version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR"
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - echo "Testing Application"
      - pip3 install flask
      - python3 test.py
      - echo "Building the Docker image"
      - docker build -t 313060132730.dkr.ecr.us-east-1.amazonaws.com/gunicorn-flask:latest .
      - docker tag 313060132730.dkr.ecr.us-east-1.amazonaws.com/gunicorn-flask 313060132730.dkr.ecr.us-east-1.amazonaws.com/gunicorn-flask:latest
  post_build:
    commands:
      - echo "Pushing the docker image"
      - docker push 313060132730.dkr.ecr.us-east-1.amazonaws.com/gunicorn-flask
artifacts:
  files:
    - imagedefinitions.json
